import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email).trim());
}

/** Phone: at least 7 digits, allows +, spaces, dashes, parens */
function isValidPhone(phone) {
  return /^[\d\s\+\-\(\)]{7,20}$/.test(String(phone).trim());
}

/** Strip HTML tags and trim */
function sanitize(value) {
  if (value === null || value === undefined) return '';
  return String(value).replace(/<[^>]*>/g, '').trim();
}

/** Submitted time in IST */
function submittedAt() {
  return new Date().toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'full',
    timeStyle: 'short',
  });
}

/** Shared row builder for HTML emails */
function row(label, value) {
  const safe = sanitize(value) || '—';
  return `
    <tr>
      <td style="padding:8px 12px;font-weight:600;color:#a78bfa;width:160px;vertical-align:top;white-space:nowrap;">
        ${label}
      </td>
      <td style="padding:8px 12px;color:#e2e8f0;">
        ${safe}
      </td>
    </tr>`;
}

/** Shared HTML email wrapper */
function buildEmail({ title, accentColor, rows }) {
  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0f0f1a;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f0f1a;padding:32px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#1a1a2e;border-radius:16px;overflow:hidden;border:1px solid #2d2d4e;">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,${accentColor});padding:28px 32px;">
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">${title}</h1>
            <p style="margin:6px 0 0;color:rgba(255,255,255,0.75);font-size:13px;">
              Taruna Technology — tarunatech.com
            </p>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:24px 32px;">
            <table width="100%" cellpadding="0" cellspacing="0"
              style="border-collapse:collapse;border:1px solid #2d2d4e;border-radius:10px;overflow:hidden;">
              ${rows}
            </table>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:16px 32px 28px;color:#6b7280;font-size:11px;border-top:1px solid #2d2d4e;">
            This email was automatically generated by the Taruna Technology website contact system.
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

// ─────────────────────────────────────────────────────────────
// Email builders — one per form type
// ─────────────────────────────────────────────────────────────

function buildConsultationEmail(data) {
  const { name, email, phone, service, message } = data;
  const html = buildEmail({
    title: '⚡ New Consultation Request',
    accentColor: '#7c3aed,#a855f7',
    rows: [
      row('Name', name),
      row('Email', email),
      row('Phone', phone),
      row('Service Interested', service || 'Not selected'),
      row('Project Description', message || 'Not provided'),
      row('Submitted', submittedAt()),
    ].join(''),
  });
  const text = [
    'NEW CONSULTATION REQUEST — Taruna Technology',
    '─'.repeat(40),
    `Name:               ${sanitize(name)}`,
    `Email:              ${sanitize(email)}`,
    `Phone:              ${sanitize(phone)}`,
    `Service Interested: ${sanitize(service) || 'Not selected'}`,
    `Project Description:${sanitize(message) || 'Not provided'}`,
    `Submitted:          ${submittedAt()}`,
  ].join('\n');
  return { subject: 'New Consultation Request — Taruna Technology', html, text };
}

function buildCourseEnrollmentEmail(data) {
  const { name, email, phone, course, message } = data;
  const html = buildEmail({
    title: '🎓 New Course Enrollment',
    accentColor: '#0891b2,#06b6d4',
    rows: [
      row('Student Name', name),
      row('Email', email),
      row('Phone', phone),
      row('Selected Course', course),
      row('Message', message || 'Not provided'),
      row('Submitted', submittedAt()),
    ].join(''),
  });
  const text = [
    'NEW COURSE ENROLLMENT — Taruna Technology',
    '─'.repeat(40),
    `Student Name:   ${sanitize(name)}`,
    `Email:          ${sanitize(email)}`,
    `Phone:          ${sanitize(phone)}`,
    `Selected Course:${sanitize(course)}`,
    `Message:        ${sanitize(message) || 'Not provided'}`,
    `Submitted:      ${submittedAt()}`,
  ].join('\n');
  return { subject: 'New Course Enrollment — Taruna Technology', html, text };
}

function buildContactEmail(data) {
  const { name, email, phone, service, message } = data;
  const html = buildEmail({
    title: '📬 New Contact Form Submission',
    accentColor: '#be185d,#ec4899',
    rows: [
      row('Name', name),
      row('Email', email),
      row('Phone', phone),
      row('Service Required', service || 'Not specified'),
      row('Message', message),
      row('Submitted', submittedAt()),
    ].join(''),
  });
  const text = [
    'NEW CONTACT FORM SUBMISSION — Taruna Technology',
    '─'.repeat(40),
    `Name:             ${sanitize(name)}`,
    `Email:            ${sanitize(email)}`,
    `Phone:            ${sanitize(phone)}`,
    `Service Required: ${sanitize(service) || 'Not specified'}`,
    `Message:          ${sanitize(message)}`,
    `Submitted:        ${submittedAt()}`,
  ].join('\n');
  return { subject: 'New Contact Form Submission — Taruna Technology', html, text };
}

function buildProductDemoEmail(data) {
  const { name, email, phone, company, message, product } = data;
  const html = buildEmail({
    title: '🚀 New Product Demo Request',
    accentColor: '#065f46,#10b981',
    rows: [
      row('Product', product),
      row('Name', name),
      row('Email', email),
      row('Phone', phone),
      row('Company', company || 'Not provided'),
      row('Requirements', message || 'Not provided'),
      row('Submitted', submittedAt()),
    ].join(''),
  });
  const text = [
    'NEW PRODUCT DEMO REQUEST — Taruna Technology',
    '─'.repeat(40),
    `Product:      ${sanitize(product)}`,
    `Name:         ${sanitize(name)}`,
    `Email:        ${sanitize(email)}`,
    `Phone:        ${sanitize(phone)}`,
    `Company:      ${sanitize(company) || 'Not provided'}`,
    `Requirements: ${sanitize(message) || 'Not provided'}`,
    `Submitted:    ${submittedAt()}`,
  ].join('\n');
  return { subject: 'New Product Demo Request — Taruna Technology', html, text };
}

// ─────────────────────────────────────────────────────────────
// Route handler
// ─────────────────────────────────────────────────────────────

// Simple in-memory rate limiter: max 5 submissions per IP per minute
const rateLimitMap = new Map();
function checkRateLimit(ip) {
  const now = Date.now();
  const window = 60_000; // 1 minute
  const max = 5;
  const entry = rateLimitMap.get(ip) || { count: 0, start: now };
  if (now - entry.start > window) {
    rateLimitMap.set(ip, { count: 1, start: now });
    return true;
  }
  if (entry.count >= max) return false;
  rateLimitMap.set(ip, { count: entry.count + 1, start: entry.start });
  return true;
}

export async function POST(request) {
  // ── Rate limit ──────────────────────────────────────────────
  const ip =
    request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ||
    request.headers.get('x-real-ip') ||
    'unknown';

  if (!checkRateLimit(ip)) {
    return NextResponse.json(
      { success: false, error: 'Too many requests. Please wait a moment and try again.' },
      { status: 429 }
    );
  }

  // ── Parse body ──────────────────────────────────────────────
  let body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { success: false, error: 'Invalid request body.' },
      { status: 400 }
    );
  }

  const { formType, ...fields } = body;

  // ── Validate formType ───────────────────────────────────────
  const VALID_FORM_TYPES = ['consultation', 'course-enrollment', 'contact', 'product-demo'];
  if (!formType || !VALID_FORM_TYPES.includes(formType)) {
    return NextResponse.json(
      { success: false, error: 'Invalid form type.' },
      { status: 400 }
    );
  }

  // ── Validate shared required fields (email + phone) ─────────
  const email = sanitize(fields.email);
  const phone = sanitize(fields.phone);

  if (!email || !isValidEmail(email)) {
    return NextResponse.json(
      { success: false, error: 'Please provide a valid email address.' },
      { status: 422 }
    );
  }
  if (!phone || !isValidPhone(phone)) {
    return NextResponse.json(
      { success: false, error: 'Please provide a valid phone number.' },
      { status: 422 }
    );
  }

  // ── Per-form validation ─────────────────────────────────────
  if (formType === 'consultation') {
    if (!sanitize(fields.name)) {
      return NextResponse.json({ success: false, error: 'Name is required.' }, { status: 422 });
    }
  }

  if (formType === 'course-enrollment') {
    if (!sanitize(fields.name)) {
      return NextResponse.json({ success: false, error: 'Full name is required.' }, { status: 422 });
    }
    if (!sanitize(fields.course)) {
      return NextResponse.json({ success: false, error: 'Please select a course.' }, { status: 422 });
    }
  }

  if (formType === 'contact') {
    if (!sanitize(fields.name)) {
      return NextResponse.json({ success: false, error: 'Name is required.' }, { status: 422 });
    }
    if (!sanitize(fields.message)) {
      return NextResponse.json({ success: false, error: 'Message is required.' }, { status: 422 });
    }
  }

  if (formType === 'product-demo') {
    if (!sanitize(fields.name)) {
      return NextResponse.json({ success: false, error: 'Name is required.' }, { status: 422 });
    }
    if (!sanitize(fields.product)) {
      return NextResponse.json({ success: false, error: 'Product name is required.' }, { status: 422 });
    }
  }

  // ── Check env vars ──────────────────────────────────────────
  const EMAIL_USER     = process.env.EMAIL_USER;
  const EMAIL_PASS     = process.env.EMAIL_PASS;
  const BUSINESS_EMAIL = process.env.BUSINESS_EMAIL;

  if (!EMAIL_USER || !EMAIL_PASS || !BUSINESS_EMAIL) {
    console.error('[send-email] Missing EMAIL_USER, EMAIL_PASS, or BUSINESS_EMAIL env vars');
    return NextResponse.json(
      { success: false, error: 'Email service is not configured. Please contact us directly.' },
      { status: 500 }
    );
  }

  // ── Build email content ─────────────────────────────────────
  let emailContent;
  const sanitizedFields = Object.fromEntries(
    Object.entries(fields).map(([k, v]) => [k, sanitize(v)])
  );

  switch (formType) {
    case 'consultation':
      emailContent = buildConsultationEmail(sanitizedFields);
      break;
    case 'course-enrollment':
      emailContent = buildCourseEnrollmentEmail(sanitizedFields);
      break;
    case 'contact':
      emailContent = buildContactEmail(sanitizedFields);
      break;
    case 'product-demo':
      emailContent = buildProductDemoEmail(sanitizedFields);
      break;
  }

  // ── Send via Nodemailer ─────────────────────────────────────
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user: EMAIL_USER, pass: EMAIL_PASS },
  });

  try {
    await transporter.sendMail({
      from: `"Taruna Technology Website" <${EMAIL_USER}>`,
      to: BUSINESS_EMAIL,
      replyTo: sanitizedFields.email,
      subject: emailContent.subject,
      text: emailContent.text,
      html: emailContent.html,
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error('[send-email] Nodemailer error:', err?.message || err);
    return NextResponse.json(
      { success: false, error: 'Failed to send email. Please try again or contact us directly.' },
      { status: 500 }
    );
  }
}
